[package]
name = "tokio-utils"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
log = { workspace = true }

[dev-dependencies]
testing_logger = "0.1"

