name: Probe resctrl/perf in QEMU guest

on:
  workflow_dispatch:
    inputs:
      image-type:
        description: 'LVH image type (e.g., ubuntu-22.04 or ubuntu-24.04)'
        required: false
        default: 'ubuntu-22.04'
        type: string
  pull_request:
    paths:
      - '.github/workflows/probe-resctrl-in-qemu.yaml'
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/probe-resctrl-in-qemu.yaml'

jobs:
  probe-in-guest:
    name: Probe in guest VM
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Provision LVH VM and run probe
        uses: yonch/little-vm-helper@main
        with:
          test-name: qemu-probe
          image: ${{ inputs.image-type || 'ubuntu-22.04' }}
          host-mount: ./
          images-folder-parent: "/tmp"
          cpu: 2
          mem: 2G
          # Enable passthrough PMU support for the guest
          cpu-kind: 'host,pmu=on'
          lvh-version: "v0.0.23"
          install-dependencies: 'true'
          verbose: 'true'
          cmd: |
            set -euxo pipefail
            LOG=/host/probe-vm.log
            exec > >(tee -a "$LOG") 2>&1

            echo "== Guest system info =="
            cat /etc/os-release || true
            uname -a
            lscpu || true
            grep -m1 -i '^flags' /proc/cpuinfo || true
            cat /proc/cmdline || true

            echo "== Kernel config: resctrl related =="
            if [ -r /proc/config.gz ]; then
              zcat /proc/config.gz | rg -i 'RESCTRL|RDT' || true
            elif [ -r "/boot/config-$(uname -r)" ]; then
              rg -i 'RESCTRL|RDT' "/boot/config-$(uname -r)" || true
            else
              echo "kernel config not readable"
            fi

            echo "== resctrl probe =="
            ls -ld /sys/fs/resctrl || true
            sudo mkdir -p /sys/fs/resctrl || true
            if ! mount | grep -q 'on /sys/fs/resctrl '; then
              sudo mount -t resctrl resctrl /sys/fs/resctrl || true
            fi
            mount | grep -i resctrl || true
            cat /proc/mounts | grep -i resctrl || true
            if [ -d /sys/fs/resctrl ]; then
              [ -f /sys/fs/resctrl/schemata ] && cat /sys/fs/resctrl/schemata || true
              [ -f /sys/fs/resctrl/info/L3/cbm_mask ] && cat /sys/fs/resctrl/info/L3/cbm_mask || true
              echo "L3_MON features:"; cat /sys/fs/resctrl/info/L3_MON/mon_features 2>/dev/null || true
              echo "L3_MON RMIDs:"; cat /sys/fs/resctrl/info/L3_MON/num_rmids 2>/dev/null || true
              echo "L3 CLOSIDs:"; cat /sys/fs/resctrl/info/L3/num_closids 2>/dev/null || true
            fi

            echo "== perf/PMU probe =="
            sysctl kernel.perf_event_paranoid || true
            sysctl kernel.kptr_restrict || true
            echo "Attempting to set perf_event_paranoid=-1"
            sudo sysctl -w kernel.perf_event_paranoid=-1 || true
            sysctl kernel.perf_event_paranoid || true

            echo "PMU sources:"
            for d in /sys/bus/event_source/devices/*; do
              [ -d "$d" ] || continue
              name=$(basename "$d")
              type=$(cat "$d/type" 2>/dev/null || echo -n '?')
              echo "$name type=$type"
            done

            if ! command -v perf >/dev/null 2>&1; then
              echo "perf not found; attempting install"
              sudo apt-get update -y || true
              sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-$(uname -r) || true
            fi
            command -v perf || true
            perf --version || true

            echo "perf list (short)"
            perf list || true
            echo "perf stat cycles for 1s"
            perf stat -e cycles -a -- sleep 1 || true

            echo "== clocksource/timers =="
            cat /sys/devices/system/clocksource/clocksource0/available_clocksource || true
            cat /sys/devices/system/clocksource/clocksource0/current_clocksource || true
            cat /proc/timer_list 2>/dev/null | head -n 200 || true

            echo "== Done =="

      - name: Upload guest probe log
        uses: actions/upload-artifact@v4
        with:
          name: qemu-guest-probe
          path: probe-vm.log
          if-no-files-found: warn

