name: Probe resctrl/perf in QEMU guest

on:
  workflow_dispatch:
    inputs:
      kernel-version:
        description: 'LVH complexity-test image version (e.g., 6.6-YYYYMMDD.HHMMSS)'
        required: false
        default: '6.6-20250507.063028'
        type: string
  pull_request:
    paths:
      - '.github/workflows/probe-resctrl-in-qemu.yaml'
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/probe-resctrl-in-qemu.yaml'

jobs:
  probe-in-guest:
    name: Probe in guest VM
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.runner == 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            image: complexity-test
            cpu_kind: 'max,pmu=on'
            install_deps: 'true'
          - runner: ubuntu-24.04-arm
            image: complexity-test-aarch64
            cpu_kind: 'max,pmu=on'
            install_deps: 'false'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare images directory
        run: |
          sudo mkdir -p /tmp/images
          sudo chmod 777 /tmp/images

      - name: Provision LVH VM and run probe
        uses: yonch/little-vm-helper@main
        with:
          test-name: qemu-probe
          image: ${{ matrix.image }}
          image-version: ${{ github.event.inputs.kernel-version || '6.6-20250507.063028' }}
          host-mount: ./
          images-folder-parent: "/tmp/images"
          cpu: 2
          mem: 2G
          # CPU model from matrix (x86 or aarch64)
          cpu-kind: ${{ matrix.cpu_kind }}
          lvh-version: "v0.0.23"
          install-dependencies: ${{ matrix.install_deps }}
          verbose: 'true'
          cmd: |
            set -euxo pipefail
            LOG=/host/probe-vm.log
            exec > >(tee -a "$LOG") 2>&1

            echo "== Guest system info =="
            cat /etc/os-release || true
            uname -a
            lscpu || true
            grep -m1 -i '^flags' /proc/cpuinfo || true
            cat /proc/cmdline || true
            echo "== Kernel config: resctrl related =="
            if [ -r /proc/config.gz ]; then
              if command -v rg >/dev/null 2>&1; then zcat /proc/config.gz | rg -i 'RESCTRL|RDT' || true; else zcat /proc/config.gz | grep -Ei 'RESCTRL|RDT' || true; fi
            elif [ -r "/boot/config-$(uname -r)" ]; then
              if command -v rg >/dev/null 2>&1; then rg -i 'RESCTRL|RDT' "/boot/config-$(uname -r)" || true; else grep -Ei 'RESCTRL|RDT' "/boot/config-$(uname -r)" || true; fi
            else
              echo "kernel config not readable"
            fi

            echo "== resctrl probe =="
            ls -ld /sys/fs/resctrl || true
            sudo mkdir -p /sys/fs/resctrl || true
            if ! mount | grep -q 'on /sys/fs/resctrl '; then
              sudo mount -t resctrl resctrl /sys/fs/resctrl || true
            fi
            mount | grep -i resctrl || true
            cat /proc/mounts | grep -i resctrl || true
            if [ -d /sys/fs/resctrl ]; then
              [ -f /sys/fs/resctrl/schemata ] && cat /sys/fs/resctrl/schemata || true
              [ -f /sys/fs/resctrl/info/L3/cbm_mask ] && cat /sys/fs/resctrl/info/L3/cbm_mask || true
              echo "L3_MON features:"; cat /sys/fs/resctrl/info/L3_MON/mon_features 2>/dev/null || true
              echo "L3_MON RMIDs:"; cat /sys/fs/resctrl/info/L3_MON/num_rmids 2>/dev/null || true
              echo "L3 CLOSIDs:"; cat /sys/fs/resctrl/info/L3/num_closids 2>/dev/null || true
            fi

            echo "== perf/PMU probe =="
            sysctl kernel.perf_event_paranoid || true
            sysctl kernel.kptr_restrict || true
            echo "Attempting to set perf_event_paranoid=-1"
            sudo sysctl -w kernel.perf_event_paranoid=-1 || true
            sysctl kernel.perf_event_paranoid || true

            echo "PMU sources:"
            for d in /sys/bus/event_source/devices/*; do
              [ -d "$d" ] || continue
              name=$(basename "$d")
              type=$(cat "$d/type" 2>/dev/null || echo -n '?')
              echo "$name type=$type"
            done

            if ! command -v perf >/dev/null 2>&1; then
              echo "perf not found; attempting install via common package managers"
              if command -v apt-get >/dev/null 2>&1; then
                sudo apt-get update -y || true
                # Try Ubuntu/Debian variants
                sudo apt-get install -y linux-tools-common || true
                sudo apt-get install -y linux-tools-$(uname -r) || true
                sudo apt-get install -y linux-tools-generic || true
                sudo apt-get install -y linux-perf || true
                sudo apt-get install -y perf || true
              elif command -v dnf >/dev/null 2>&1; then
                sudo dnf install -y perf || true
              elif command -v yum >/dev/null 2>&1; then
                sudo yum install -y perf || true
              elif command -v zypper >/dev/null 2>&1; then
                sudo zypper --non-interactive install perf || true
              elif command -v apk >/dev/null 2>&1; then
                sudo apk add --no-cache linux-perf || true
                sudo apk add --no-cache perf || true
              else
                echo "No known package manager detected for perf installation"
              fi
            fi
            command -v perf || true
            perf --version || true

            echo "perf list (short)"
            perf list || true
            echo "perf stat cycles for 1s"
            perf stat -e cycles -a -- sleep 1 || true

            echo "== clocksource/timers =="
            cat /sys/devices/system/clocksource/clocksource0/available_clocksource || true
            cat /sys/devices/system/clocksource/clocksource0/current_clocksource || true
            cat /proc/timer_list 2>/dev/null | head -n 200 || true

            echo "== Done =="

      - name: Upload guest probe log
        uses: actions/upload-artifact@v4
        with:
          name: qemu-guest-probe
          path: probe-vm.log
          if-no-files-found: warn
