name: reusable-test-resctrl

on:
  workflow_call:
    inputs:
      level:
        description: Test level (cheap-short|perf-short|full-short|full-long)
        required: true
        type: string
      instance-type:
        description: EC2 instance type for resctrl-capable host
        required: false
        default: m7i.metal-24xl
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: false
      REPO_ADMIN_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache cargo registry and git index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-resctrl-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-resctrl-cargo-

      - name: Cache cargo build artifacts
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-resctrl-target-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-resctrl-target-

      - name: Install Rust toolchain
        run: |
          rustc -V || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "source $HOME/.cargo/env" >> $HOME/.profile
          source $HOME/.cargo/env
          rustc -V
          cargo -V

      - name: Build smoke test binary (no-run)
        run: |
          source $HOME/.cargo/env
          cargo test -p resctrl --test smoke_test --release --no-run

      - name: Build nri-resctrl-plugin integration tests (no-run)
        run: |
          source $HOME/.cargo/env
          # Build all integration tests for nri-resctrl-plugin without running them
          cargo test -p nri-resctrl-plugin --tests --release --no-run


      - name: Collect smoke test binary
        run: |
          set -euxo pipefail
          BIN=$(find target/release/deps -maxdepth 1 -type f -executable -name 'smoke_test-*' | head -n 1)
          test -n "$BIN" || { echo "smoke test bin not found"; exit 1; }
          cp "$BIN" resctrl-smoke
          chmod +x resctrl-smoke

      - name: Upload resctrl smoke binary
        uses: actions/upload-artifact@v4
        with:
          name: resctrl-smoke-bin
          path: resctrl-smoke
          if-no-files-found: error

      - name: Collect nri-resctrl-plugin e2e binary
        id: collect-plugin-bin
        run: |
          set -euxo pipefail
          P_BIN=$(find target/release/deps -maxdepth 1 -type f -executable -name 'integration_test-*' | head -n 1)
          test -n "$P_BIN" || { echo "nri-resctrl-plugin integration test binary not found"; exit 1; }
          cp "$P_BIN" nri-resctrl-plugin-e2e
          chmod +x nri-resctrl-plugin-e2e

      - name: Upload nri-resctrl-plugin e2e binary
        uses: actions/upload-artifact@v4
        with:
          name: nri-resctrl-plugin-e2e
          path: nri-resctrl-plugin-e2e
          if-no-files-found: error

  nri-resctrl-plugin-e2e:
    name: NRI resctrl plugin full flow (k3s on EC2)
    needs: [setup-runner, build, resctrl-e2e-smoke]
    runs-on: ${{ needs.setup-runner.outputs.runner-label }}
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup k3s
        uses: ./.github/actions/setup-k3s
        with:
          kubeconfig_path: /etc/rancher/k3s/k3s.yaml
          disable_packaged_addons: true
          preflight_inotify: true
          wait_kube_system: false
          timeout_api_server_ready_seconds: 300
          timeout_node_ready_seconds: 300

      - name: Verify NRI socket
        uses: ./.github/actions/nri-socket-exists

      - name: Download nri-resctrl-plugin e2e binary
        uses: actions/download-artifact@v4
        with:
          name: nri-resctrl-plugin-e2e
          path: ./

      - name: Prepare test binary
        run: |
          chmod +x ./nri-resctrl-plugin-e2e || true

      - name: Wait for resctrl RMID GC (mon_groups creatable)
        shell: bash
        run: |
          echo "Ensuring resctrl RMIDs are garbage-collected before tests..."
          MON_GROUPS="/sys/fs/resctrl/mon_groups"
          if [ ! -d "$MON_GROUPS" ]; then
            echo "resctrl mon_groups directory not found at $MON_GROUPS"
            exit 1
          fi
          # Try to create and remove a dummy mon_group every second for up to 20 seconds
          for i in $(seq 1 20); do
            name="gha-gc-check-$RANDOM-$(date +%s)"
            dir="$MON_GROUPS/$name"
            if sudo mkdir "$dir" 2>/dev/null; then
              echo "Successfully created $dir on attempt $i"
              # Clean up immediately after success
              sudo rmdir "$dir" || sudo rm -rf "$dir" || true
              exit 0
            fi
            sleep 1
          done
          echo "Failed to create a mon_group directory after 20 seconds; RMIDs may still be exhausted."
          exit 1

      - name: Run plugin integration tests (excluding capacity retry)
        env:
          NRI_SOCKET_PATH: /var/run/nri/nri.sock
          RUST_LOG: info
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          echo "Using prebuilt test binary: ./nri-resctrl-plugin-e2e"
          NRI_SOCKET_PATH="/var/run/nri/nri.sock" sudo -E ./nri-resctrl-plugin-e2e --include-ignored --nocapture --test-threads=1 --skip test_capacity_retry_e2e

      - name: Run plugin integration test (capacity retry)
        env:
          NRI_SOCKET_PATH: /var/run/nri/nri.sock
          RUST_LOG: info
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          echo "Using prebuilt test binary: ./nri-resctrl-plugin-e2e"
          NRI_SOCKET_PATH="/var/run/nri/nri.sock" sudo -E ./nri-resctrl-plugin-e2e test_capacity_retry_e2e --include-ignored --nocapture --test-threads=1
      - name: Cleanup k3s
        if: always()
        run: |
          sudo /usr/local/bin/k3s-uninstall.sh || true


  setup-runner:
    if: inputs.level == 'full-short' || inputs.level == 'full-long'
    name: Start EC2 runner (resctrl-capable)
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-runner.outputs.runner-label }}
      ec2-instance-id: ${{ steps.start-runner.outputs.ec2-instance-id }}
      region: ${{ steps.start-runner.outputs.region }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start AWS Runner
        id: start-runner
        uses: ./.github/actions/aws-runner
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          iam-role-name: github-actions-runner
          instance-type: ${{ inputs.instance-type }}
          image-type: ubuntu-24.04
          market-type: spot

  resctrl-e2e-smoke:
    if: inputs.level == 'full-short' || inputs.level == 'full-long'
    name: Run resctrl smoke test
    needs: [build, setup-runner]
    runs-on: ${{ needs.setup-runner.outputs.runner-label }}
    timeout-minutes: 20
    env:
      HOME: /root
    steps:
      - name: Prepare HOME
        run: mkdir -p "$HOME"
      - name: Download smoke binary
        uses: actions/download-artifact@v4
        with:
          name: resctrl-smoke-bin
          path: ./
      - name: Run resctrl smoke test (hardware)
        shell: bash
        run: |
          set -euxo pipefail
          BIN=./resctrl-smoke
          chmod +x "$BIN" || true
          RESCTRL_E2E=1 "$BIN" --nocapture --test-threads=1

  stop-runner:
    if: always() && (inputs.level == 'full-short' || inputs.level == 'full-long')
    name: Stop EC2 runner
    needs: [setup-runner, resctrl-e2e-smoke, nri-resctrl-plugin-e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Stop AWS Runner
        uses: ./.github/actions/aws-runner/cleanup
        with:
          runner-label: ${{ needs.setup-runner.outputs.runner-label }}
          ec2-instance-id: ${{ needs.setup-runner.outputs.ec2-instance-id }}
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ needs.setup-runner.outputs.region }}
