name: rust-lints

on:
  push:
    # Run on any branch push, filtered to Rust workspace changes
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-lints.yaml'

jobs:
  lint:
    name: Clippy and fmt (workspace)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with components
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libelf-dev pkg-config zlib1g-dev

      - name: Cache cargo and target
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy (deny warnings)
        run: |
          cargo clippy --workspace --all-features --all-targets --locked -- -D warnings
